"""Generate ``docs/data_contracts.md`` from the Pydantic schemas and the SQL schema (RSF-050).

Run ``python -m research_factory.contracts_doc`` after changing a contract; a test fails
when the committed document is stale.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from .domain.models import AuditEvent, EvidenceRef, Finding
from .domain.project_models import (
    ApprovalRecord,
    BacktestSpec,
    Experiment,
    Hypothesis,
    StepResult,
    WorkflowRun,
)
from .judgment.contract import JudgmentOutput
from .persistence.schema import APPEND_ONLY_TABLES, metadata

MODELS: list[tuple[type[BaseModel], str]] = [
    (Hypothesis, "A research hypothesis. Frozen: any change makes a new experiment."),
    (BacktestSpec, "How the hypothesis is tested. `as_of` is the knowledge cutoff."),
    (Experiment, "Hypothesis + backtest spec. `experiment_id` is a content hash of both."),
    (WorkflowRun, "One execution of the workflow for an experiment."),
    (StepResult, "The persisted outcome of one step; completed results are immutable."),
    (EvidenceRef, "An immutable, content-addressed piece of evidence."),
    (Finding, "A conclusion with severity, confidence and cited evidence."),
    (AuditEvent, "An append-only record of something that happened."),
    (ApprovalRecord, "A human committee decision."),
    (JudgmentOutput, "What a judgment step (model or rules) must return."),
]


def _fields(schema: dict[str, Any]) -> list[str]:
    required = set(schema.get("required", []))
    rows = []
    for name, prop in schema.get("properties", {}).items():
        kind = (
            prop.get("type")
            or prop.get("$ref", "").rsplit("/", 1)[-1]
            or " | ".join(
                str(p.get("type") or p.get("$ref", "").rsplit("/", 1)[-1]) for p in prop.get("anyOf", [])
            )
        )
        if prop.get("format"):
            kind = f"{kind} ({prop['format']})"
        constraints = ", ".join(
            f"{k}={prop[k]}"
            for k in ("minimum", "exclusiveMinimum", "maximum", "minLength", "maxLength", "pattern", "enum")
            if k in prop
        )
        rows.append(f"| `{name}` | {kind} | {'yes' if name in required else ''} | {constraints} |")
    return rows


def render() -> str:
    out = [
        "# Data contracts",
        "",
        "Generated by `python -m research_factory.contracts_doc` from the Pydantic models and the SQL schema. "
        "Do not edit by hand.",
        "",
        "All datetimes are timezone-aware and normalized to UTC; naive datetimes are rejected.",
        "",
    ]
    for model, description in MODELS:
        schema = model.model_json_schema(mode="serialization")
        out += [
            f"## {model.__name__}",
            "",
            description,
            "",
            "| Field | Type | Required | Constraints |",
            "|---|---|---|---|",
        ]
        out += _fields(schema)
        defs = schema.get("$defs", {})
        for name, sub in sorted(defs.items()):
            if "properties" in sub:
                out += [
                    "",
                    f"**{name}**",
                    "",
                    "| Field | Type | Required | Constraints |",
                    "|---|---|---|---|",
                    *_fields(sub),
                ]
            elif "enum" in sub:
                out += ["", f"**{name}**: one of {', '.join(f'`{v}`' for v in sub['enum'])}"]
        out.append("")
    out += [
        "## Relational schema",
        "",
        f"Append-only tables (database triggers reject UPDATE and DELETE): "
        f"{', '.join(f'`{t}`' for t in APPEND_ONLY_TABLES)}.",
        "",
    ]
    for table in metadata.sorted_tables:
        out += [f"### `{table.name}`", "", "| Column | Type | Nullable | Key |", "|---|---|---|---|"]
        for col in table.columns:
            key = (
                "PK"
                if col.primary_key
                else (
                    "FK → " + ", ".join(fk.target_fullname for fk in col.foreign_keys)
                    if col.foreign_keys
                    else ""
                )
            )
            out.append(f"| `{col.name}` | {col.type} | {'yes' if col.nullable else 'no'} | {key} |")
        out.append("")
    out += [
        "## Tool error format",
        "",
        "Errors are returned as MCP `isError` results whose text contains:",
        "",
        "```json",
        json.dumps({"error": {"code": "AS_OF_REQUIRED", "message": "...", "details": {}}}, indent=2),
        "```",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("docs/data_contracts.md")
    path.write_text(render(), encoding="utf-8")
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
